version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: doneq
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - '27017-27019:27017-27019'

volumes:
  mongodb_data_container:
